from flask import Flask, render_template, url_for, request
from elasticsearch import Elasticsearch
app = Flask(__name__)
    
# Fingerprint either from Elasticsearch startup or above script.
# Colons and uppercase/lowercase don't matter when using
# the 'ssl_assert_fingerprint' parameter
CERT_FINGERPRINT = "88:F9:62:77:0E:2A:BC:8F:E5:A0:0D:83:4A:00:BD:B2:29:5A:03:FD:86:43:20:E4:BE:12:4C:D6:27:DA:93:CD"

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "2l1Dpk6fHCqV8oDUg242"

client = Elasticsearch(
    "https://localhost:9200",
    ssl_assert_fingerprint=CERT_FINGERPRINT,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
print(client.info())

dataretrived = []

def mapsearchdata(searchedresults):
    global dataretrived
    dataretrived.clear()
    for ahit in searchedresults['hits']['hits']:
        dataretrived.append(ahit["_source"])
    

@app.route("/", methods=["POST", "GET"])
def home():
    global client
    
    if request.method == "POST":
        userquery = request.form["userquery"]
        operator = request.form["operator"]
        searchpara = request.form["wheretosearch"]
        resultsize = int(request.form["resultsize"])
        
        
        searchedresults = client.search(index="ap89", query={"match": {searchpara: {"query": userquery, "operator": operator}}}, size=resultsize)
        mapsearchdata(searchedresults)
        return render_template("searchresults.html", datadisplay=dataretrived, searchquerytext=userquery)
    else:
        return render_template("index.html")



if __name__ == '__main__':
    app.run(debug=True)