import json
from elasticsearch import Elasticsearch
    
# Fingerprint either from Elasticsearch startup or above script.
# Colons and uppercase/lowercase don't matter when using
# the 'ssl_assert_fingerprint' parameter
CERT_FINGERPRINT = "88:F9:62:77:0E:2A:BC:8F:E5:A0:0D:83:4A:00:BD:B2:29:5A:03:FD:86:43:20:E4:BE:12:4C:D6:27:DA:93:CD"

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "2l1Dpk6fHCqV8oDUg242"

client = Elasticsearch(
    "https://localhost:9200",
    ssl_assert_fingerprint=CERT_FINGERPRINT,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
client.info()
client.indices.create(index="ap89")
# client.indices.delete(index="ap89")


data = {}

def loaddata():
    global data
    with open('parsed_file.json') as json_file:
        data = json.load(json_file)
    return True
    
    
def indexdata():
    if loaddata():
        for docid in data.keys():
            print(client.index(index="ap89", id=docid, document=data[docid]))
    else:
        print("FILE PARSING FAILED")
        
indexdata()